services:
  jammy:
    build:
      context: .
      dockerfile: Dockerfile.matrix
      args:
        BASE_IMAGE: ubuntu:22.04
    volumes:
      - ./dist:/dist:ro

  noble:
    build:
      context: .
      dockerfile: Dockerfile.matrix
      args:
        BASE_IMAGE: ubuntu:24.04
    volumes:
      - ./dist:/dist:ro

  resolute:
    build:
      context: .
      dockerfile: Dockerfile.matrix
      args:
        BASE_IMAGE: ubuntu:26.04
    volumes:
      - ./dist:/dist:ro
