ARG BASE_IMAGE=ubuntu:26.04
FROM ${BASE_IMAGE}
ENV DEBIAN_FRONTEND=noninteractive

COPY debian/install-and-verify.sh /usr/local/bin/install-and-verify.sh
COPY debian/verify-install.sh /usr/local/bin/verify-install.sh
RUN chmod 0755 /usr/local/bin/install-and-verify.sh /usr/local/bin/verify-install.sh

CMD ["/usr/local/bin/install-and-verify.sh"]
